name: verify-serenity-project

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  execute-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run tests
        run: mvn clean test -Denvironments=web
